import assert from 'node:assert/strict'
import test from 'node:test'
import { readFile } from 'node:fs/promises'

test('UI lifecycle is Runtime-only, generation-guarded, and wires Core ready-vector inputs', async () => {
  const mainSource = await readFile(new URL('./main.jsx', import.meta.url), 'utf8')
  const settingsSource = await readFile(new URL('./SettingsWorkspace.jsx', import.meta.url), 'utf8')
  const researchSource = await readFile(new URL('./features/research/ResearchWorkspace.jsx', import.meta.url), 'utf8')
  const providerSource = await readFile(new URL('./providerConfig.js', import.meta.url), 'utf8')
  assert.match(mainSource, /runtimeAdapter\.retrievalIndexes\.(status|progress|build|rebuild|cancel|read)/)
  assert.match(mainSource, /retrievalIndexOperationRef\.current\.generation !== generation/)
  assert.match(mainSource, /validateReadyRetrievalIndex\(readResult, identity\)/)
  assert.match(mainSource, /BioResearch OS embedding dimension probe\./)
  assert.match(mainSource, /validateEmbeddingDimensionProbe\(probeResult/)
  assert.match(mainSource, /withProviderModelDimensions\(providerConfigs/)
  assert.match(mainSource, /retrievalIndexOperationRef\.current\.generation !== generation/)
  assert.ok(mainSource.indexOf("modelConfig.remoteEmbeddingConsent !== true") < mainSource.indexOf('query: EMBEDDING_DIMENSION_PROBE_TEXT'))
  assert.ok(mainSource.indexOf('validateEmbeddingDimensionProbe(probeResult') < mainSource.indexOf('createRetrievalIndexBuildInput({ identity'))
  assert.ok(mainSource.indexOf('withProviderModelDimensions(providerConfigs') < mainSource.indexOf('createRetrievalIndexBuildInput({ identity'))
  assert.match(mainSource, /if \(!operation\.building && !operation\.identity\) return/)
  assert.match(mainSource, /controller\.signal\.aborted \? 'cancelled'/)
  assert.match(providerSource, /mergeDiscoveredProviderModels/)
  assert.equal((mainSource.match(/setReadyRetrievalIndex\(\{/g) || []).length, 1)
  assert.ok(mainSource.indexOf('setReadyRetrievalIndex({') > mainSource.indexOf('if (validated.ok)'))
  assert.match(mainSource, /vectorIndex:/)
  assert.match(mainSource, /requestedIndexIdentity:/)
  assert.match(providerSource, /embeddingDimensions/)
  assert.doesNotMatch(mainSource, /window\.localStorage.*retrieval|localStorage.*vector|fetch\(/)
  assert.match(settingsSource, /Cancel build/)
  assert.match(settingsSource, /Rebuild index/)
  assert.match(settingsSource, /remoteEmbeddingConsent/)
  assert.match(settingsSource, /Use in Retrieval/)
  assert.doesNotMatch(settingsSource, /Not used yet/)
  assert.match(researchSource, /retrievalFocus/)
  assert.match(researchSource, /safeRetrievalErrorMessage/)
  assert.match(researchSource, /citation source/)
})

test('dimension probe continues to build in the same invocation before publishing React provider state', async () => {
  const mainSource = await readFile(new URL('./main.jsx', import.meta.url), 'utf8')
  const start = mainSource.indexOf('const startRetrievalIndexBuild = useCallback')
  const end = mainSource.indexOf('const cancelRetrievalIndexBuild = useCallback', start)
  const flow = mainSource.slice(start, end)
  const probe = flow.indexOf('retrievalRuntime.embedding.embed({ query: EMBEDDING_DIMENSION_PROBE_TEXT')
  const persist = flow.indexOf('saveProviderConfigs(probedProviderConfigs)')
  const buildMethod = flow.indexOf('runtimeAdapter.retrievalIndexes.build')
  const invokeBuild = flow.indexOf('method({')
  const applyResult = flow.indexOf('await applyRetrievalIndexResult(result, identity, generation, controller.signal)')
  const publishState = flow.indexOf('setProviderConfigs(probedProviderConfigs)')
  assert.ok(start >= 0 && end > start)
  assert.ok(probe >= 0 && persist > probe)
  assert.ok(buildMethod > persist && invokeBuild > buildMethod)
  assert.ok(applyResult > invokeBuild && publishState > applyResult)
  assert.equal(flow.slice(probe, invokeBuild).includes('setProviderConfigs('), false)
  assert.match(flow, /retrievalIndexOperationRef\.current\.generation === generation/)
})
